### PR TITLE
Fix AMQPConnection::setPort() writes to wrong property

### PR DESCRIPTION
**Pull request by pinepain**
Fixes https://github.com/pdezwart/php-amqp/issues/188.

This is simple copy-paste garbage cleanup after refactoring.

No BC breaking, no extra requirements.

### CODE REVIEW

**Comment by pkruithof** [comment]
Got another inconsistency: `AMQPQueue::setName()` does not return `true`, all the other setters do.

**Comment by pinepain** [comment]
@pkruithof, good catch. Fixed and squashed. But returning `true` in setters in most places is useless while we just update object property. I guess later we will get rid of it, but for now let's be consistent. Thanks.

**Comment by pkruithof** [comment]
I caught it because I'm writing a library which uses this extension as a driver :wink: 

I agree it's practically useless when false is never returned (AFAIK), but it doesn't hurt and indicates the operation worked. I wouldn't change it (but I'm obviously biased since I would have to update the library in this case).

**Comment by pinepain** [comment]
@pkruithof, I already add `return true` to `AMQPQueue::setName()` in this PR, so now it is consistent (at least in this part).

**Comment by pkruithof** [comment]
I know, it was a reply on this statement:

> I guess later we will get rid of it, but for now let's be consistent.

**Comment by lstrojny** [comment]
@pinepain I consider returning true in the setters a bug. Can we make them return null now already?

**Comment by pinepain** [comment]
@lstrojny, for sure, but this will break BC. Currently this is a trivial fix to stay consistent, though, I totally agree that in our case setters should return nothing (`@return void` annotation in stubs).

**Comment by pinepain** [comment]
@lstrojny, can we merge this as it fixes major issue (see https://github.com/pdezwart/php-amqp/pull/189/files#diff-40f7cdf3f96d4346a1418ce7a7af8e92L846 line) as we start receiving more bug reports related to it #188 and fresh one #192 and roll pecl release?

**Comment by lstrojny** [comment]
@pinepain sure

**Comment by pinepain** [comment]
Just a tiny minor note, new alpha2 marked as beta =).

**Pull request merged**
