### PR TITLE
Proper support AMQP for array and timestamp types for dead lettering

### PR DESCRIPTION
**Pull request by lstrojny**
PR for #271

### CODE REVIEW

**Comment by lstrojny** [comment]
@pinepain The array changes are now ready for review. I extracted `amqp_type` file to handle all the type conversion logic.

**Comment by lstrojny** [comment]
@remicollet as I don’t have a windows build environment, would you mind building this branch on windows and running the tests?

**Comment by remicollet** [comment]
@lstrojny sorry, I don't even know what Windows is ;)

**Comment by pinepain** [comment]
@lstrojny maybe appveyour could help? e.g. here is config I use in php-ref - https://github.com/pinepain/php-ref/blob/master/appveyor.yml, though, not sure how to install librabbitmq-c.

Alternatively, we could release on pecl and see how it will go 😄.

**Pull request merged**
