### PR TITLE
Add a link to amqp interop compatible transport.

### PR DESCRIPTION
**Pull request by makasim**

### CODE REVIEW

**Comment by pinepain** [comment]
Nice work, thanks!

I'd suggest to put abstractions and libraries into separate section (there would be more than one, I hope). Also, you may add `[skip ci]` to commit message as we don't run tests on readme file 😄 yet.

**Comment by lstrojny** [comment]
Agreed, separate section makes sense. Otherwise I like the idea of cross-pollination in the PHP AMQP space 👍

**Comment by makasim** [comment]
btw, there are RabbitMQ official tutorials adopted to amqp interop. They are working for amqp ext as well 

https://github.com/php-enqueue/enqueue-dev/tree/master/pkg/amqp-lib/tutorial

**Comment by makasim** [comment]
@pinepain @lstrojny Should I do something more to get it merged?

**Comment by lstrojny** [comment]
@makasim sorry for the late response. I would like to add a "Related libraries" section instead and as part of that section mention the interop project

**Comment by makasim** [comment]
@lstrojny done

**Comment by lstrojny** [comment]
Thanks for your contribution and your patience!

**Pull request merged**
