### PR TITLE
Add PHP support check for #316 

### PR DESCRIPTION
**Pull request by yjqg6666**
Only PHP version >= 5.6 could compile. See #316

### CODE REVIEW

**Comment by pinepain** [comment]
Awesome, thanks! Would you mind to add a note to readme that PHP 5.6 required, e.g. to alter `This extension works both with PHP 5 and PHP 7 (both zts and non-zts).` to sth like `This extension works both with PHP >= 5.6 (including PHP 7) with both zts and non-zts versions.` or any other variations you will find reasonable.

**Comment by yjqg6666** [comment]
@pinepain The README updated. I put it into the requirement section.

**Comment by lstrojny** [comment]
Thank you!

**Comment by ryandesign** [comment]
The pecl page still says it supports PHP 5.3 or later.

**Comment by lstrojny** [comment]
The change has not yet been released, that’s why it still says 5.3

**Comment by ryandesign** [comment]
Yes it has. [amqp 1.9.4 was released to pecl](https://pecl.php.net/package/amqp/1.9.4). It requires PHP 5.6 or newer, but the pecl page says it requires 5.3 or newer, which is wrong.

**Comment by lstrojny** [comment]
I don’t think so. Have a look at the package.xml in 1.9.4: https://github.com/pdezwart/php-amqp/blob/12bab1199e91f9193d759aa4297dc5d1ceac071e/package.xml

```
    <dependencies>
        <required>
            <php>
                <min>5.3.0</min>
            </php>
            <pearinstaller>
                <min>1.4.0</min>
            </pearinstaller>
        </required>
    </dependencies>

```

**Comment by lstrojny** [comment]
@ryandesign well, that’s why this changed in master (https://github.com/pdezwart/php-amqp/blob/master/package.xml)

```xml
    <dependencies>
        <required>
            <php>
                <min>5.6.0</min>
            </php>
            <pearinstaller>
                <min>1.4.0</min>
            </pearinstaller>
        </required>
    </dependencies>
```

**Comment by ryandesign** [comment]
Ok great, thanks. I don't suppose there's a way to fix the pecl web site to indicate that 1.9.4 in fact requires 5.6, without having to repackage the tarball?

**Pull request merged**
