### PR TITLE
return true on all set*-methods in AMQPExchange

### PR DESCRIPTION
**Pull request by prolic**

### CODE REVIEW

**Comment by pinepain** [comment]
It was already discussed earlier: unless setter method may fail, it considered void. Setter methods that do remote calls, e.g. `AMQPChannel::setPrefetchCount()` which do `basic.qos` call under the hood may fail, and when it fail it throws exception. 

If there any violations of this rule in current codebase, it still so for BC saving reason and is subject to change in next major release, if any.

**Comment by pinepain** [comment]
What is the reason to do this?

**Comment by prolic** [comment]
I just noticed, that other methods return true after settings, f.e. here: https://github.com/pdezwart/php-amqp/blob/master/amqp_exchange.c#L280

Addtionally the return value is documented in the stubs, see here: https://github.com/pdezwart/php-amqp/blob/master/stubs/AMQPExchange.php#L225

So either we have to add the return value on the setters or update documentation.

**Comment by lstrojny** [comment]
Thanks for pointing out the inconsistency, that’s indeed incorrect. All setter should be void methods.

**Comment by prolic** [comment]
Ok, I'll open a new PR

**Comment by prolic** [comment]
Btw: what about this one?

https://github.com/pdezwart/php-amqp/blob/master/amqp_connection.c#L961

**Comment by prolic** [comment]
new PR here: https://github.com/pdezwart/php-amqp/pull/208

**Comment by pinepain** [comment]
@prolic `php_amqp_disconnect_force()` throws exception in case it fail, so the only result that `AMQPConnection::setReadTimeout()` may return is `true`, if it fail it throws `AMQPConnectionException` exception.

**Pull request closed without merging**
