### PR TITLE
fix minimal librabbitmq in config.m4 and readme

### PR DESCRIPTION
**Pull request by remicollet**
Consistency with 52ee7f6a19d4db5b9b4a01385e52ba2fb4728d7e

### CODE REVIEW

**Comment by lstrojny** [comment]
Sorry @remicollet for letting this slip, still relevant?

**Comment by remicollet** [comment]
> still relevant?

Yes, I thinkg so

**Comment by lstrojny** [comment]
@remicollet could you rebase to see if the tests pass?

**Comment by remicollet** [comment]
rebased (btw, travis seem stalled)

**Comment by remicollet** [comment]
Minor typo fixed (breaking test with old pkg-config version)

**Comment by lstrojny** [comment]
Thank you @remicollet

**Pull request merged**
