### PR TITLE
Fix segmentation fault

### PR DESCRIPTION
**Pull request by vstepanyuk**
Related to https://github.com/pdezwart/php-amqp/issues/190

### CODE REVIEW

**Comment by pinepain** [comment]
Does the problem still happens against my branch in PR https://github.com/pdezwart/php-amqp/pull/194?

**Comment by vstepanyuk** [comment]
Problem solved in 1.7.0alpha1, but it's still alpha.

**Comment by vstepanyuk** [comment]
It fix segmentation fault if two times call setAttributes on AMQPQueue

**Comment by pinepain** [comment]
I guess we'll release stable 1.7 soon. That pr I mentioned above fixes a lot, so I guess it is ready for production, try it. If anything, feels free to submit and issue here or post to existent one.

**Comment by lstrojny** [comment]
Thanks for the fix!

**Comment by vstepanyuk** [comment]
@lstrojny @pinepain when do you plan to release 1.6 version with this fix?

**Comment by pinepain** [comment]
@vstepanyuk Lars had to release, maybe he is overloaded on work or something like that, but let's ping him one more time. Is it option to you to switch to 1.7 branch? It is BC compatible with 1.6 (but some recent changes are also waiting for a release).

**Comment by vstepanyuk** [comment]
@pinepain 1.7 still in beta channel, will be fine to use stable channel

**Comment by pinepain** [comment]
@vstepanyuk  1.7 has many fixes 1.6 doesn't have, but it's all up to you. At least give it a look.

**Comment by vstepanyuk** [comment]
@pinepain I will

**Pull request merged**
